<div class="container h-100">
  <div class="d-flex justify-content-center align-items-center h-100">
    <div class="card" style="width: 36rem; border-radius: 20px;">
      <div class="card-body">

         <div class="d-flex justify-content-center">
            <img src="IMG/twitter_logo.png" />
         </div>

        <div class="text-center mb-2">
          <h2>Cadastro realizado com sucesso</h2>
        </div>
          <!-- / = Redireciona para o diretório raiz-->
          <a href="/" class="btn btn-primary btn-block" style="border-radius: 20px;">Clique aqui para fazer login!</a>

      </div>
    </div>
  </div>
</div>



    
  